"""Tests for security/upload: extension, magic bytes, size, sanitization."""
import io
import pytest

from core.errors import UploadError
from security import upload


def test_allowed_extension():
    assert upload.allowed_extension("test.txt")
    assert upload.allowed_extension("test.docx")
    assert upload.allowed_extension("test.PDF")  # case-insensitive
    assert upload.allowed_extension("file.MD")
    assert not upload.allowed_extension("test.exe")
    assert not upload.allowed_extension("test")
    assert not upload.allowed_extension("")
    assert not upload.allowed_extension(None)


def test_check_size():
    upload.check_size(1024)  # OK
    with pytest.raises(UploadError):
        upload.check_size(0)
    with pytest.raises(UploadError):
        upload.check_size(30 * 1024 * 1024)  # > 25 MB cap


def test_magic_bytes_pdf():
    pdf_content = b"%PDF-1.4 rest of pdf"
    upload.check_magic_bytes(pdf_content, "pdf")  # should pass
    with pytest.raises(UploadError):
        upload.check_magic_bytes(b"not a pdf", "pdf")


def test_magic_bytes_docx():
    docx_content = b"PK\x03\x04 zip data"
    upload.check_magic_bytes(docx_content, "docx")  # should pass
    with pytest.raises(UploadError):
        upload.check_magic_bytes(b"not a docx", "docx")


def test_magic_bytes_text_formats_skip_check():
    # Text formats are not checked by magic bytes (no universal signature)
    upload.check_magic_bytes(b"hello", "txt")
    upload.check_magic_bytes(b"# Markdown", "md")
    upload.check_magic_bytes(b"<html>", "html")


def test_sanitize_filename():
    assert upload.sanitize_filename("simple.txt") == "simple.txt"
    assert upload.sanitize_filename("../../etc/passwd") == "passwd"
    assert upload.sanitize_filename("path/to/file.txt") == "file.txt"
    assert upload.sanitize_filename("") == "upload"
    assert upload.sanitize_filename("...hidden") == "hidden"
    # Unicode normalization
    assert "é" in upload.sanitize_filename("café.txt") or "_" in upload.sanitize_filename("café.txt")


def test_strip_unsafe_html():
    html = '<script>alert("xss")</script><p onclick="evil()">text</p>'
    cleaned = upload.strip_unsafe_html(html)
    assert "<script" not in cleaned.lower()
    assert "onclick" not in cleaned.lower()
    assert "<p" in cleaned


def test_parse_uploaded_file_txt():
    text, fmt = upload.parse_uploaded_file("test.txt", b"Hello world.")
    assert fmt == "txt"
    assert "Hello world" in text


def test_parse_uploaded_file_md():
    text, fmt = upload.parse_uploaded_file("note.md", b"# Title\n\nParagraph.")
    assert fmt == "md"
    assert "Title" in text


def test_parse_uploaded_file_rtf():
    """Real RTF content should be parsed correctly."""
    # Real RTF starts with {\rtf — backslashes are literal in RTF
    rtf = b'{\\rtf1\\ansi\\ansicpg1252\\deff0{\\fonttbl{\\f0\\fnil Calibri;}}\\f0\\fs22 Hello RTF world.\\par Second paragraph.}'
    text, fmt = upload.parse_uploaded_file("test.rtf", rtf)
    assert fmt == "rtf"
    assert "Hello RTF" in text
    assert "Second paragraph" in text


def test_parse_uploaded_file_docx():
    """Real DOCX generated by python-docx should parse correctly."""
    import io
    from docx import Document
    doc = Document()
    doc.add_paragraph("DOCX paragraph one.")
    doc.add_paragraph("DOCX paragraph two.")
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    text, fmt = upload.parse_uploaded_file("test.docx", buf.getvalue())
    assert fmt == "docx"
    assert "DOCX paragraph one" in text
    assert "DOCX paragraph two" in text


def test_parse_uploaded_file_odt():
    """Real ODT generated by odfpy should parse correctly."""
    import io
    from odf.opendocument import OpenDocumentText
    from odf.text import P
    odt_doc = OpenDocumentText()
    odt_doc.text.addElement(P(text="ODT paragraph content."))
    buf = io.BytesIO()
    odt_doc.save(buf)
    buf.seek(0)
    text, fmt = upload.parse_uploaded_file("test.odt", buf.getvalue())
    assert fmt == "odt"
    assert "ODT paragraph content" in text


def test_parse_uploaded_file_html_strips_scripts():
    """HTML with scripts should be sanitized."""
    html = b'<html><body><script>alert(1)</script><p>Safe content</p></body></html>'
    text, fmt = upload.parse_uploaded_file("test.html", html)
    assert fmt == "html"
    assert "Safe content" in text
    assert "alert" not in text


def test_parse_uploaded_file_csv():
    text, fmt = upload.parse_uploaded_file("data.csv", b"col1,col2\nval1,val2")
    assert fmt == "csv"
    assert "col1" in text


def test_parse_uploaded_file_bad_magic():
    # File claims to be PDF but content isn't
    with pytest.raises(UploadError):
        upload.parse_uploaded_file("fake.pdf", b"not really a pdf")


def test_parse_uploaded_file_unsupported():
    with pytest.raises(UploadError):
        upload.parse_uploaded_file("file.exe", b"binary")


def test_safe_join_rejects_traversal():
    from pathlib import Path
    from core.errors import ValidationError
    root = Path("/tmp/asm-test-root")
    root.mkdir(exist_ok=True)
    try:
        # Normal path
        result = upload.safe_join(root, "subdir", "file.txt")
        assert str(result).startswith(str(root.resolve()))
        # Traversal attempt
        with pytest.raises(ValidationError):
            upload.safe_join(root, "..", "..", "etc", "passwd")
    finally:
        root.rmdir()
